"""Add crypto withdrawal fields to WithdrawalRequest

Revision ID: 7a9bc5265bde
Revises: efc4364fcab6
Create Date: 2025-12-04 04:40:57.237530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a9bc5265bde'
down_revision = 'efc4364fcab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdrawal_method', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('wallet_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('crypto_network', sa.String(length=50), nullable=True))
        batch_op.alter_column('account_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('account_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('bank_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_request', schema=None) as batch_op:
        batch_op.alter_column('bank_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('account_number',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('account_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('crypto_network')
        batch_op.drop_column('wallet_address')
        batch_op.drop_column('withdrawal_method')

    # ### end Alembic commands ###
