"""initial migration

Revision ID: efc4364fcab6
Revises: 
Create Date: 2025-12-02 21:21:09.391527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc4364fcab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=False),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('min_price_usd', sa.Float(), nullable=False),
    sa.Column('max_price_usd', sa.Float(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('dividend_percentage', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('referral_code', sa.String(length=10), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['referred_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('user_package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('investment_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_proof_url', sa.String(length=255), nullable=True),
    sa.Column('depositor_name', sa.String(length=120), nullable=True),
    sa.Column('depositor_bank', sa.String(length=120), nullable=True),
    sa.Column('deposited_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawal_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_package_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_package_id'], ['user_package.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_package_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal_request')
    op.drop_table('user_package')
    op.drop_table('user')
    op.drop_table('package')
    # ### end Alembic commands ###
